name: Android CI

on:
  push:
    branches:
      - main
      - nouvellebr

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Installer Java 17 (au lieu de Java 11)
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Rendre gradlew exécutable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build
